# Generated by Django 3.1.8 on 2021-04-27 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='name',
            new_name='cand_name',
        ),
    ]
