# Generated by Django 3.2.3 on 2021-06-01 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_auto_20210427_1517'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
